# Generated by Django 3.2.9 on 2021-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tasks',
            field=models.ManyToManyField(to='task.Task'),
        ),
    ]
